# Generated by Django 5.0.2 on 2024-03-29 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tests', '0004_alter_test_next_test'),
        ('videos', '0002_video_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='questions',
        ),
        migrations.AddField(
            model_name='video',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='my_tests.test'),
        ),
        migrations.AddField(
            model_name='video',
            name='user_watched',
            field=models.ManyToManyField(blank=True, null=True, related_name='watched_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
