# Generated by Django 5.0.2 on 2024-03-29 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_questions_video_test_video_user_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user_watched',
            field=models.ManyToManyField(blank=True, related_name='watched_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
