# Generated by Django 5.0.2 on 2024-03-31 10:35

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile__class_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Другое', 'Другое')], default='Другое', max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='_class',
            field=models.CharField(max_length=4, validators=[users.validators.validate_class], verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('Кыргызский', 'Кыргызский'), ('Русский', 'Русский'), ('Английский', 'Английский')], max_length=50, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, validators=[users.validators.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=100, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='Специальзация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(max_length=100, verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=150, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Учитель', 'Учитель'), ('Студент', 'Студент')], default='Студент', max_length=100, null=True, verbose_name='Роль'),
        ),
    ]
